---

- name: ensure elasticsearch service started and enabled
  service:
    name: elasticsearch
    state: started
    enabled: true

- name: restart elasticsearch service
  debug:
    msg: "restart elasticsearch"
  changed_when: true
  when: force_restart | default('no') | bool
  notify:
    - elasticsearch restart
    - elasticsearch service status
    - elasticsearch health check
    - elasticsearch health check message
