---

- name: systemd daemon reload
  systemd:
    daemon_reload: true
  when: ansible_os_family | lower == "redhat" and ansible_distribution_major_version >= '7' or
        ansible_os_family | lower == "debian" and ansible_distribution_major_version >= '8'

- name: elasticsearch restart
  service:
    name: elasticsearch
    state: restarted

- name: elasticsearch service status
  wait_for:
    host: "{{ elasticsearch.config.network.bind_host }}"
    port: "{{ elasticsearch.config.http.port }}"
    delay: 60

- name: elasticsearch health check
  uri:
    url: http://{{ elasticsearch.config.network.bind_host }}:{{ elasticsearch.config.http.port }}/_cluster/health?pretty
    method: GET
    return_content: true
    timeout: 120
  register: es_health_check
  until: es_health_check.status == 200
  retries: 20
  delay: 10

- name: elasticsearch health check message
  debug:
    msg: "{{ (es_health_check.content|from_json) }}"

- name: elasticsearch hold version
  dpkg_selections:
    name: elasticsearch
    selection: hold
  when: elasticsearch.pin_version

- name: elasticsearch lock version
  command: yum versionlock add elasticsearch-{{ elasticsearch.version }}
  args:
    warn: false
  when: elasticsearch.pin_version
