---

- name: ensure dependencies are installed
  package:
    name:
      - curl
      - yum-utils
      - libselinux-python
      - policycoreutils-python
      - java-1.8.0-openjdk.x86_64

- name: ensure Elastic repository is present
  yum_repository:
    name: "elastic-{{ elasticsearch.version.split('.')[:1] | join('.') }}.x"
    description: "Elastic repository for version {{ elasticsearch.version.split('.')[:1] | join('.') }}.x"
    file: "elastic-{{ elasticsearch.version.split('.')[:1] | join('.') }}.x"
    baseurl: "https://artifacts.elastic.co/packages/{{ elasticsearch.version.split('.')[:1] | join('.') }}.x/yum"
    gpgkey: "http://packages.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: true
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: ensure yum-plugin-versionlock is installed
  package:
    name: yum-plugin-versionlock
  when: elasticsearch.pin_version
